### ISSUE TITLE
期望加入github actions build 

### ISSUE THREAD

**Issue by xiaosi-ss** [unbored/JianziNote#1]
RT 本地编译一直有问题……

**Comment by unbored** [comment]
什么样的问题不妨描述一下？建议用vcpkg解决依赖。

**Comment by unbored** [comment]
已加入actions build，可以从action的最新结果的artifact当中下到程序。

**Comment by xiaosi-ss** [comment]
> 已加入actions build，可以从action的最新结果的artifact当中下到程序。

dalao yyds
